import fs from "node:fs"

// import { normalize } from "node:path"
type Feature = {
  properties?: {
    shapeName?: string
  }
}

// adjust this path to your actual file
const geojson = JSON.parse(
	fs.readFileSync("./public/geojson/india/allStates.json", "utf-8"),
)

const normalize = (s: string) =>
  s.trim().toLowerCase().replace(/\s+/g, " ")

const districtSet = new Set([
	"Aravalli",
	"Agra",
	"Aligarh",
	"Allahabad",
	"Ambedkar Nagar",
	"Amethi",
	"Amroha", // (Jyotiba Phule Nagar)
	"Auraiya",
	"Azamgarh",
	"Budaun",
	"Baghpat",
	"Bahraich",
	"Ballia",
	"Balrampur",
	"Banda",
	"Barabanki",
	"Bareilly",
	"Basti",
	"Bijnor",
	"Bulandshahr",
	"Chandauli",
	"Chitrakoot",
	"Deoria",
	"Etah",
	"Etawah",
	"Ayodhya", // Faizabad renamed
	"Farrukhabad",
	"Fatehpur",
	"Firozabad",
	"Gautam Buddha Nagar",
	"Ghaziabad",
	"Ghazipur",
	"Gonda",
	"Gorakhpur",
	"Hamirpur",
	"Hapur",
	"Hardoi",
	"Hathras", // Mahamaya Nagar
	"Jalaun",
	"Jaunpur",
	"Jhansi",
	"Kannauj",
	"Kanpur Dehat",
	"Kanpur Nagar",
	"Kasganj", // Kanshiram Nagar
	"Kaushambi",
	"Kushinagar",
	"Lakhimpur Kheri",
	"Lalitpur",
	"Lucknow",
	"Maharajganj",
	"Mahoba",
	"Mainpuri",
	"Mathura",
	"Mau",
	"Meerut",
	"Mirzapur",
	"Moradabad",
	"Muzaffarnagar",
	"Pilibhit",
	"Pratapgarh",
	"Prayagraj", // Allahabad renamed
	"Raebareli",
	"Rampur",
	"Saharanpur",
	"Sambhal",
	"Sant Kabir Nagar",
	"Sant Ravidas Nagar (Bhadohi)",
	"Shahjahanpur",
	"Shamli",
	"Shravasti",
	"Siddharthnagar",
	"Sitapur",
	"Sonbhadra",
	"Sultanpur",
	"Unnao",
	"Varanasi",
	"Agar",
	"Alirajpur",
	"Anuppur",
	"Ashoknagar",
	"Balaghat",
	"Barwani",
	"Betul",
	"Bhind",
	"Bhopal",
	"Burhanpur",
	"Chhatarpur",
	"Chhindwara",
	"Damoh",
	"Datia",
	"Dewas",
	"Dhar",
	"Dindori",
	"Guna",
	"Gwalior",
	"Harda",
	"Narmadapuram", // Hoshangabad (modern name)
	"Indore",
	"Jabalpur",
	"Jhabua",
	"Katni",
	"Khandwa (East Nimar)",
	"Khargone (West Nimar)",
	"Mandla",
	"Mandsaur",
	"Morena",
	"Narsimhapur",
	"Neemuch",
	"Panna",
	"Raisen",
	"Rajgarh",
	"Ratlam",
	"Rewa",
	"Sagar",
	"Satna",
	"Sehore",
	"Seoni",
	"Shahdol",
	"Shajapur",
	"Sheopur",
	"Shivpuri",
	"Sidhi",
	"Singrauli",
	"Tikamgarh",
	"Ujjain",
	"Umaria",
	"Vidisha",
	"Niari", // (sometimes Niwari appears as Niwari — check dataset)
	"Dindori",
	"Mandla",
	"Ajmer",
	"Alwar",
	"Banswara",
	"Baran",
	"Barmer",
	"Bharatpur",
	"Bhilwara",
	"Bikaner",
	"Bundi",
	"Chittaurgarh",
	"Churu",
	"Dhaulpur",
	"Dungarpur",
	"Ganganagar",
	"Hanumangarh",
	"Jaipur",
	"Jaisalmer",
	"Jalor",
	"Jhalawar",
	"Jhunjhunun",
	"Jodhpur",
	"Karauli",
	"Kota",
	"Nagaur",
	"Pali",
	"Pratapgarh",
	"Rajsamand",
	"Sawai Madhopur",
	"Sikar",
	"Sirohi",
	"Tonk",
	"Udaipur",
	"Ariyalur",
	"Chengalpattu",
	"Chennai",
	"Coimbatore",
	"Cuddalore",
	"Dharmapuri",
	"Dindigul",
	"Erode",
	"Kallakurichi",
	"Kancheepuram",
	"Kanniyakumari",
	"Karur",
	"Krishnagiri",
	"Madurai",
	"Mayiladuthurai",
	"Nagapattinam",
	"Namakkal",
	"Nilgiris",
	"Perambalur",
	"Pudukkottai",
	"Ramanathapuram",
	"Ranipet",
	"Salem",
	"Sivaganga",
	"Tenkasi",
	"Thanjavur",
	"Theni",
	"Thoothukudi",
	"Tiruchirappalli",
	"Tirunelveli",
	"Tirupathur",
	"Tiruppur",
	"Tiruvallur",
	"Tiruvannamalai",
	"Tiruvarur",
	"Vellore",
	"Viluppuram",
	"Virudhunagar",
	"Araria",
	"Arwal",
	"Aurangabad",
	"Banka",
	"Begusarai",
	"Bhagalpur",
	"Bhojpur",
	"Buxar",
	"Darbhanga",
	"Gaya",
	"Gopalganj",
	"Jamui",
	"Jehanabad",
	"Kaimur (Bhabua)",
	"Katihar",
	"Khagaria",
	"Kishanganj",
	"Lakhisarai",
	"Madhepura",
	"Madhubani",
	"Munger",
	"Muzaffarpur",
	"Nalanda",
	"Nawada",
	"Patna",
	"Purnia",
	"Rohtas",
	"Saharsa",
	"Samastipur",
	"Saran",
	"Sheikhpura",
	"Sheohar",
	"Sitamarhi",
	"Siwan",
	"Supaul",
	"Vaishali",
	"West Champaran",
	"East Champaran",
	"Mumbai",
	"Mumbai Suburban",
	"Thane",
	"Palghar",
	"Raigarh",
	"Ratnagiri",
	"Sindhudurg",
	"Nashik",
	"Dhule",
	"Nandurbar",
	"Jalgaon",
	"Ahmadnagar",
	"Pune",
	"Solapur",
	"Satara",
	"Sangli",
	"Kolhapur",
	"Aurangabad",
	"Jalna",
	"Parbhani",
	"Hingoli",
	"Bid",
	"Nanded",
	"Osmanabad",
	"Latur",
	"Buldana",
	"Akola",
	"Washim",
	"Amravati",
	"Yavatmal",
	"Wardha",
	"Nagpur",
	"Bhandara",
	"Gondiya",
	"Chandrapur",
	"Gadchiroli",
	"Baksa",
	"Barpeta",
	"Biswanath",
	"Bongaigaon",
	"Cachar",
	"Charaideo",
	"Chirang",
	"Darrang",
	"Dhemaji",
	"Dhubri",
	"Dibrugarh",
	"Dima Hasao",
	"Goalpara",
	"Golaghat",
	"Hailakandi",
	"Hojai",
	"Jorhat",
	"Kamrup",
	"Kamrup Metropolitan",
	"Karbi Anglong East",
	"Karbi Anglong West",
	"Kokrajhar",
	"Lakhimpur",
	"Majuli",
	"Morigaon",
	"Nagaon",
	"Nalbari",
	"Sivasagar",
	"Sonitpur",
	"South Salmara-Mankachar",
	"Tinsukia",
	"Udalguri",
	"Adilabad",
	"Bhadradri",
	"Hyderabad",
	"Jagtial",
	"Jangaon",
	"Jayashankar",
	"Jogulamba",
	"Kamareddy",
	"Karimnagar",
	"Khammam",
	"Komaram Bheem",
	"Mahabubabad",
	"Mahabubnagar",
	"Mancherial",
	"Medak",
	"Medchal",
	"Nagarkurnool",
	"Nalgonda",
	"Narayanpet",
	"Nirmal",
	"Nizamabad",
	"Peddapalli",
	"Rajanna Sircilla",
	"Rangareddy",
	"Sangareddy",
	"Siddipet",
	"Suryapet",
	"Vikarabad",
	"Wanaparthy",
	"Warangal (R)",
	"Warangal (U)",
	"Yadadri Bhongiri",
	"Balod",
	"Baloda Bazar",
	"Balrampur",
	"Bastar",
	"Bemetra",
	"Bijapur",
	"Bilaspur",
	"Dakshin Bastar Dantewada",
	"Dhamtari",
	"Durg",
	"Gariaband",
	"Gaurella Pendra Marwahi",
	"Janjgir-Champa",
	"Jashpur",
	"Kabirdham",
	"Kanker",
	"Kondagaon",
	"Korba",
	"Koriya",
	"Mahasamund",
	"Mungeli",
	"Narayanpur",
	"Raigarh",
	"Raipur",
	"Rajnandgaon",
	"Sukma",
	"Surajpur",
	"Surguja",
	"Ahmadabad",
	"Amreli",
	"Anand",
	"Banas Kantha",
	"Bharuch",
	"Bhavnagar",
	"Chhota Udaipur",
	"Dohad",
	"The Dangs",
	"Gandhinagar",
	"Gir Somnath",
	"Jamnagar",
	"Junagadh",
	"Kachchh",
	"Kheda",
	"Mahesana",
	"Mahisagar",
	"Morbi",
	"Narmada",
	"Navsari",
	"Panch Mahals",
	"Patan",
	"Porbandar",
	"Rajkot",
	"Sabar Kantha",
	"Surat",
	"Surendranagar",
	"Tapi",
	"Vadodara",
	"Valsad",
	"Bagalkot",
	"Ballari",
	"Belagavi",
	"Bengaluru Rural",
	"Bengaluru Urban",
	"Bidar",
	"Chamarajanagar",
	"Chikkaballapura",
	"Chikkamagaluru",
	"Chitradurga",
	"Dakshina Kannada",
	"Davanagere",
	"Dharwad",
	"Gadag",
	"Hassan",
	"Haveri",
	"Kalaburagi",
	"Kodagu",
	"Kolar",
	"Koppal",
	"Mandya",
	"Mysuru",
	"Raichur",
	"Ramanagara",
	"Shivamogga",
	"Tumakuru",
	"Udupi",
	"Uttara Kannada",
	"Vijayanagara",
	"Vijayapura",
	"Yadgir",
	"Anugul",
	"Balangir",
	"Baleshwar",
	"Bargarh",
	"Bhadrak",
	"Boudh",
	"Cuttack",
	"Debagarh",
	"Dhenkanal",
	"Gajapati",
	"Ganjam",
	"Jagatsinghapur",
	"Jajapur",
	"Jharsuguda",
	"Kalahandi",
	"Kandhamal",
	"Kendrapara",
	"Kendujhar",
	"Khordha",
	"Koraput",
	"Malkangiri",
	"Mayurbhanj",
	"Nabarangapur",
	"Nayagarh",
	"Nuapada",
	"Puri",
	"Rayagada",
	"Sambalpur",
	"Subarnapur",
	"Sundargarh",
	"Anantapur",
	"Chittoor",
	"East Godavari",
	"Guntur",
	"Krishna",
	"Kurnool",
	"Sri Potti Sriramulu Nellore",
	"Prakasam",
	"Srikakulam",
	"Visakhapatnam",
	"Vizianagaram",
	"West Godavari",
	"Y.S.R. Kadapa",
	"Anjaw",
	"Changlang",
	"Dibang Valley",
	"East Kameng",
	"East Siang",
	"Kamle",
	"Kra Daadi",
	"Kurung Kumey",
	"Lepa Rada",
	"Lohit",
	"Longding",
	"Lower Dibang Valley",
	"Lower Siang",
	"Lower Subansiri",
	"Namsai",
	"Pakke Kessang",
	"Papum Pare",
	"Shi Yomi",
	"Siang",
	"Tawang",
	"Tirap",
	"Upper Siang",
	"Upper Subansiri",
	"West Kameng",
	"West Siang",
	"Bokaro",
	"Chatra",
	"Deoghar",
	"Dhanbad",
	"Dumka",
	"East Singhbhum",
	"Garhwa",
	"Giridih",
	"Godda",
	"Gumla",
	"Hazaribagh",
	"Jamtara",
	"Khunti",
	"Koderma",
	"Latehar",
	"Lohardaga",
	"Pakur",
	"Palamu",
	"Ramgarh",
	"Ranchi",
	"Sahibganj",
	"Saraikela-Kharsawan",
	"Simdega",
	"West Singhbhum",
	"Alipurduar",
	"Bankura",
	"Birbhum",
	"Cooch Behar",
	"Dakshin Dinajpur",
	"Darjiling",
	"Hooghly",
	"Howrah",
	"Jalpaiguri",
	"Jhargram",
	"Kalimpong",
	"Kolkata",
	"Maldah",
	"Murshidabad",
	"Nadia",
	"North 24 Parganas",
	"Paschim Medinipur",
	"Barddhaman",
	"Paschim Bardhaman",
	"Purba Medinipur",
	"Puruliya",
	"South 24 Parganas",
	"Uttar Dinajpur",
	"Amritsar",
	"Barnala",
	"Bathinda",
	"Faridkot",
	"Fatehgarh Sahib",
	"Fazilka",
	"Firozpur",
	"Gurdaspur",
	"Hoshiarpur",
	"Jalandhar",
	"Kapurthala",
	"Ludhiana",
	"Mansa",
	"Moga",
	"Sri Muktsar Sahib",
	"Pathankot",
	"Patiala",
	"Rupnagar",
	"Sahibzada Ajit Singh Nagar",
	"Sangrur",
	"Shahid Bhagat Singh Nagar",
	"Tarn Taran",
	"Ambala",
	"Bhiwani",
	"Charkhi Dadri",
	"Faridabad",
	"Fatehabad",
	"Gurugram",
	"Hisar",
	"Jhajjar",
	"Jind",
	"Kaithal",
	"Karnal",
	"Kurukshetra",
	"Mahendragarh",
	"Nuh",
	"Palwal",
	"Panchkula",
	"Panipat",
	"Rewari",
	"Rohtak",
	"Sirsa",
	"Sonipat",
	"Yamunanagar",
	"Anantnag",
	"Bandipore",
	"Baramula",
	"Budgam",
	"Doda",
	"Ganderbal",
	"Jammu",
	"Kathua",
	"Kishtwar",
	"Kulgam",
	"Kupwara",
	"Poonch",
	"Pulwama",
	"Rajouri",
	"Ramban",
	"Reasi",
	"Samba",
	"Shopian",
	"Srinagar",
	"Udhampur",
	"Alappuzha",
	"Ernakulam",
	"Idukki",
	"Kannur",
	"Kasaragod",
	"Kollam",
	"Kottayam",
	"Kozhikode",
	"Malappuram",
	"Palakkad",
	"Pathanamthitta",
	"Thiruvananthapuram",
	"Thrissur",
	"Wayanad",
	"Almora",
	"Bageshwar",
	"Chamoli",
	"Champawat",
	"Dehradun",
	"Haridwar",
	"Nainital",
	"Pauri Garhwal",
	"Pithoragarh",
	"Rudraprayag",
	"Tehri Garhwal",
	"Udham Singh Nagar",
	"Uttarkashi",
	"Bilaspur",
	"Chamba",
	"Hamirpur",
	"Kangra",
	"Kinnaur",
	"Kullu",
	"Lahaul And Spiti",
	"Mandi",
	"Shimla",
	"Sirmaur",
	"Solan",
	"Una",
	"Bishnupur",
	"Chandel",
	"Churachandpur",
	"Imphal East",
	"Imphal West",
	"Jiribam",
	"Kakching",
	"Kamjong",
	"Kangpokpi",
	"Noney",
	"Pherzawl",
	"Senapati",
	"Tamenglong",
	"Thoubal",
	"Ukhrul",
	"Dimapur",
	"Kiphire",
	"Kohima",
	"Longleng",
	"Mokokchung",
	"Mon",
	"Peren",
	"Phek",
	"Tuensang",
	"Wokha",
	"Zunheboto",
	"East Garo Hills",
	"East Jaintia Hills",
	"East Khasi Hills",
	"North Garo Hills",
	"Ri Bhoi",
	"South Garo Hills",
	"South West Garo Hills",
	"South West Khasi Hills",
	"West Garo Hills",
	"West Jaintia Hills",
	"West Khasi Hills",
	"Dhalai",
	"Gomati",
	"Khowai",
	"North Tripura",
	"Sepahijala",
	"South Tripura",
	"Unokoti",
	"West Tripura",
	"East District",
	"North District",
	"Pakyong",
	"Soreng",
	"South District",
	"West District",
	"North Goa",
	"South Goa",
	"Central Delhi",
	"East Delhi",
	"New Delhi",
	"North Delhi",
	"North East Delhi",
	"North West Delhi",
	"Shahdara",
	"South Delhi",
	"South East Delhi",
	"South West Delhi",
	"West Delhi",
	"Karaikal",
	"Mahe",
	"Puducherry",
	"Yanam",
	"Chandigarh",
	"Kargil",
	"Leh(Ladakh)",
	"Lakshadweep",
	"Nicobars",
	"North & Middle Andaman",
	"South Andaman",
	"Dadra & Nagar Haveli",
	"Daman",
	"Diu",
	"Aizawl",
	"Champhai",
	"Kolasib",
	"Lawngtlai",
	"Lunglei",
	"Mamit",
	"Saiha",
	"Serchhip",
	"Hnahthial",
	"Khawzawl",
	"Saitual"
].map(normalize))

const geoDistricts = new Set(
  (geojson.features as Feature[])
    .map((f) => f.properties?.shapeName)
    .filter((s): s is string => typeof s === "string")
    .map(normalize)
)

// 🔥 DIFFERENCE: GeoJSON - DistrictSet
const notInDistrictSet: string[] = []

for (const d of geoDistricts) {
  if (!districtSet.has(d)) {
    notInDistrictSet.push(d)
  }
}

notInDistrictSet.sort()

console.log(`❌ In GeoJSON but NOT in districtSet: ${notInDistrictSet.length}\n`)

let i = 1
for (const name of notInDistrictSet) {
  console.log(`${i++}: ${name}`)
}
// ------------------------------------------------------------------------
// const geoDistricts = new Set(
// 	geojson.features
// 		.map((f: any) => f?.properties?.shapeName)
// 		.filter(Boolean),
// )

// // intersection
// const matched: string[] = []

// for (const d of districtSet) {
// 	if (geoDistricts.has(d)) {
// 		matched.push(d)
// 	}
// }

// matched.sort()

// console.log(`Matched districts: ${matched.length}\n`)

// let count = 1
// for (const name of matched) {
// 	console.log(`${count++}: ${name}`)
// }
// ---------------------------------------------------------------------------------------------------
// const districts = geojson.features
// 	.map((f: any) => f?.properties?.shapeName)
// 	.filter(Boolean)

// // remove duplicates (just in case)
// const uniqueDistricts = [...new Set(districts)]

// // sort alphabetically for readability
// uniqueDistricts.sort()

// console.log(`Total districts: ${uniqueDistricts.length}\n`)
// let count = 1

// for (const name of uniqueDistricts) {
// 	console.log(`${count++}: ${name}`)
// }
