/** biome-ignore-all lint/suspicious/noExplicitAny: <explanation> */
import fs from "node:fs"
import path from "node:path"

const geojson = JSON.parse(
	fs.readFileSync("./public/geojson/india/allStates.json", "utf-8"),
)

// Uttar Pradesh — 75
// Madhya Pradesh — 55
// Rajasthan — 41
// Tamil Nadu — 38
// Bihar — 38
// Maharashtra — 36
// Assam — 35
// Telangana — 33
// Chhattisgarh — 33
// Gujarat — 33
// Karnataka — 31
// Odisha — 30
// Andhra Pradesh — 26
// Arunachal Pradesh — 26
// Jharkhand — 24
// West Bengal — 23
// Punjab — 23
// Haryana — 22
// Jammu and Kashmir (UT) — 20
// Kerala — 14
// Uttarakhand — 13
// Himachal Pradesh — 12
// Manipur — 16
// Nagaland — 16
// Meghalaya — 12
// Tripura — 8
// Sikkim — 6
// Goa — 2
// 🔵 Union Territories (very low / special cases)
// Delhi (NCT) — 11
// Puducherry — 4
// Chandigarh — 1
// Ladakh — 2
// Lakshadweep — 1
// Andaman & Nicobar Islands — 3
// Dadra & Nagar Haveli and Daman & Diu — 3
// ============================
// STATE MAP
// ============================
const stateDistrictMap: Record<string, string[]> = {
	UttarPradesh: [
		"Agra",
		"Aligarh",
		"Prayagraj",
		"Ambedkar Nagar",
		"Amethi",
		"Amroha", // (Jyotiba Phule Nagar)
		"Auraiya",
		"Azamgarh",
		"Budaun",
		"Baghpat",
		"Bahraich",
		"Ballia",
		"Balrampur",
		"Banda",
		"Barabanki",
		"Bareilly",
		"Basti",
		"Bijnor",
		"Bulandshahr",
		"Chandauli",
		"Chitrakoot",
		"Deoria",
		"Etah",
		"Etawah",
		"Ayodhya", // Faizabad renamed
		"Farrukhabad",
		"Fatehpur",
		"Firozabad",
		"Gautam Buddha Nagar",
		"Ghaziabad",
		"Ghazipur",
		"Gonda",
		"Gorakhpur",
		"Hamirpur",
		"Hapur",
		"Hardoi",
		"Hathras", // Mahamaya Nagar
		"Jalaun",
		"Jaunpur",
		"Jhansi",
		"Kannauj",
		"Kanpur Dehat",
		"Kanpur Nagar",
		"Kasganj", // Kanshiram Nagar
		"Kaushambi",
		"Kushinagar",
		"Lakhimpur Kheri",
		"Lalitpur",
		"Lucknow",
		"Maharajganj",
		"Mahoba",
		"Mainpuri",
		"Mathura",
		"Mau",
		"Meerut",
		"Mirzapur",
		"Moradabad",
		"Muzaffarnagar",
		"Pilibhit",
		"Pratapgarh",
		"Raebareli",
		"Rampur",
		"Saharanpur",
		"Sambhal",
		"Sant Kabir Nagar",
		"Sant Ravidas Nagar (Bhadohi)",
		"Shahjahanpur",
		"Shamli",
		"Shravasti",
		"Siddharthnagar",
		"Sitapur",
		"Sonbhadra",
		"Sultanpur",
		"Unnao",
		"Varanasi",
	],
	MadhyaPradesh: [
		"Agar",
		"Alirajpur",
		"Anuppur",
		"Ashoknagar",
		"Balaghat",
		"Barwani",
		"Betul",
		"Bhind",
		"Bhopal",
		"Burhanpur",
		"Chhatarpur",
		"Chhindwara",
		"Damoh",
		"Datia",
		"Dewas",
		"Dhar",
		"Dindori",
		"Guna",
		"Gwalior",
		"Harda",
		"Narmadapuram", // Hoshangabad (modern name)
		"Indore",
		"Jabalpur",
		"Jhabua",
		"Katni",
		"Khandwa (East Nimar)",
		"Khargone (West Nimar)",
		"Mandla",
		"Mandsaur",
		"Morena",
		"Narsimhapur",
		"Neemuch",
		"Panna",
		"Raisen",
		"Rajgarh",
		"Ratlam",
		"Rewa",
		"Sagar",
		"Satna",
		"Sehore",
		"Seoni",
		"Shahdol",
		"Shajapur",
		"Sheopur",
		"Shivpuri",
		"Sidhi",
		"Singrauli",
		"Tikamgarh",
		"Ujjain",
		"Umaria",
		"Vidisha",
		"Niari", // (sometimes Niwari appears as Niwari — check dataset)
		"Dindori",
		"Mandla",
	],
	Rajasthan: [
		"Ajmer",
		"Alwar",
		"Banswara",
		"Baran",
		"Barmer",
		"Bharatpur",
		"Bhilwara",
		"Bikaner",
		"Bundi",
		"Chittaurgarh",
		"Churu",
		"Dhaulpur",
		"Dungarpur",
		"Ganganagar",
		"Hanumangarh",
		"Jaipur",
		"Jaisalmer",
		"Jalor",
		"Jhalawar",
		"Jhunjhunun",
		"Jodhpur",
		"Karauli",
		"Kota",
		"Nagaur",
		"Pali",
		"Pratapgarh",
		"Rajsamand",
		"Sawai Madhopur",
		"Sikar",
		"Sirohi",
		"Tonk",
		"Udaipur",
	],
	TamilNadu: [
		"Ariyalur",
		"Chengalpattu",
		"Chennai",
		"Coimbatore",
		"Cuddalore",
		"Dharmapuri",
		"Dindigul",
		"Erode",
		"Kallakurichi",
		"Kancheepuram",
		"Kanniyakumari",
		"Karur",
		"Krishnagiri",
		"Madurai",
		"Mayiladuthurai",
		"Nagapattinam",
		"Namakkal",
		"Nilgiris",
		"Perambalur",
		"Pudukkottai",
		"Ramanathapuram",
		"Ranipet",
		"Salem",
		"Sivaganga",
		"Tenkasi",
		"Thanjavur",
		"Theni",
		"Thoothukudi",
		"Tiruchirappalli",
		"Tirunelveli",
		"Tirupathur",
		"Tiruppur",
		"Tiruvallur",
		"Tiruvannamalai",
		"Tiruvarur",
		"Vellore",
		"Viluppuram",
		"Virudhunagar",
	],
	Bhar: [
		"Araria",
		"Arwal",
		"Aurangabad",
		"Banka",
		"Begusarai",
		"Bhagalpur",
		"Bhojpur",
		"Buxar",
		"Darbhanga",
		"Gaya",
		"Gopalganj",
		"Jamui",
		"Jehanabad",
		"Kaimur (Bhabua)",
		"Katihar",
		"Khagaria",
		"Kishanganj",
		"Lakhisarai",
		"Madhepura",
		"Madhubani",
		"Munger",
		"Muzaffarpur",
		"Nalanda",
		"Nawada",
		"Patna",
		"Purnia",
		"Rohtas",
		"Saharsa",
		"Samastipur",
		"Saran",
		"Sheikhpura",
		"Sheohar",
		"Sitamarhi",
		"Siwan",
		"Supaul",
		"Vaishali",
		"West Champaran",
		"East Champaran",
	],
	Maharashtra: [
		"Mumbai",
		"Mumbai Suburban",
		"Thane",
		"Palghar",
		"Raigarh",
		"Ratnagiri",
		"Sindhudurg",
		"Nashik",
		"Dhule",
		"Nandurbar",
		"Jalgaon",
		"Ahmadnagar",
		"Pune",
		"Solapur",
		"Satara",
		"Sangli",
		"Kolhapur",
		"Aurangabad",
		"Jalna",
		"Parbhani",
		"Hingoli",
		"Bid",
		"Nanded",
		"Osmanabad",
		"Latur",
		"Buldana",
		"Akola",
		"Washim",
		"Amravati",
		"Yavatmal",
		"Wardha",
		"Nagpur",
		"Bhandara",
		"Gondiya",
		"Chandrapur",
		"Gadchiroli",
	],
	Assam: [
		"Baksa",
		"Barpeta",
		"Biswanath",
		"Bongaigaon",
		"Cachar",
		"Charaideo",
		"Chirang",
		"Darrang",
		"Dhemaji",
		"Dhubri",
		"Dibrugarh",
		"Dima Hasao",
		"Goalpara",
		"Golaghat",
		"Hailakandi",
		"Hojai",
		"Jorhat",
		"Kamrup",
		"Kamrup Metropolitan",
		"Karbi Anglong East",
		"Karbi Anglong West",
		"Kokrajhar",
		"Lakhimpur",
		"Majuli",
		"Morigaon",
		"Nagaon",
		"Nalbari",
		"Sivasagar",
		"Sonitpur",
		"South Salmara-Mankachar",
		"Tinsukia",
		"Udalguri",
	],
	Telangana: [
		"Adilabad",
		"Bhadradri",
		"Hyderabad",
		"Jagtial",
		"Jangaon",
		"Jayashankar",
		"Jogulamba",
		"Kamareddy",
		"Karimnagar",
		"Khammam",
		"Komaram Bheem",
		"Mahabubabad",
		"Mahabubnagar",
		"Mancherial",
		"Medak",
		"Medchal",
		"Nagarkurnool",
		"Nalgonda",
		"Narayanpet",
		"Nirmal",
		"Nizamabad",
		"Peddapalli",
		"Rajanna Sircilla",
		"Rangareddy",
		"Sangareddy",
		"Siddipet",
		"Suryapet",
		"Vikarabad",
		"Wanaparthy",
		"Warangal (R)",
		"Warangal (U)",
		"Yadadri Bhongiri",
	],
	Chhattisgarh: [
		"Balod",
		"Baloda Bazar",
		"Balrampur",
		"Bastar",
		"Bemetra",
		"Bijapur",
		"Bilaspur",
		"Dakshin Bastar Dantewada",
		"Dhamtari",
		"Durg",
		"Gariaband",
		"Gaurella Pendra Marwahi",
		"Janjgir-Champa",
		"Jashpur",
		"Kabirdham",
		"Kanker",
		"Kondagaon",
		"Korba",
		"Koriya",
		"Mahasamund",
		"Mungeli",
		"Narayanpur",
		"Raigarh",
		"Raipur",
		"Rajnandgaon",
		"Sukma",
		"Surajpur",
		"Surguja",
	],
	Gujarat: [
		"Aravalli",
		"Ahmadabad",
		"Amreli",
		"Anand",
		"Banas Kantha",
		"Bharuch",
		"Bhavnagar",
		"Chhota Udaipur",
		"Dohad",
		"The Dangs",
		"Gandhinagar",
		"Gir Somnath",
		"Jamnagar",
		"Junagadh",
		"Kachchh",
		"Kheda",
		"Mahesana",
		"Mahisagar",
		"Morbi",
		"Narmada",
		"Navsari",
		"Panch Mahals",
		"Patan",
		"Porbandar",
		"Rajkot",
		"Sabar Kantha",
		"Surat",
		"Surendranagar",
		"Tapi",
		"Vadodara",
		"Valsad",
	],
	Karnataka: [
		"Bagalkot",
		"Ballari",
		"Belagavi",
		"Bengaluru Rural",
		"Bengaluru Urban",
		"Bidar",
		"Chamarajanagar",
		"Chikkaballapura",
		"Chikkamagaluru",
		"Chitradurga",
		"Dakshina Kannada",
		"Davanagere",
		"Dharwad",
		"Gadag",
		"Hassan",
		"Haveri",
		"Kalaburagi",
		"Kodagu",
		"Kolar",
		"Koppal",
		"Mandya",
		"Mysuru",
		"Raichur",
		"Ramanagara",
		"Shivamogga",
		"Tumakuru",
		"Udupi",
		"Uttara Kannada",
		"Vijayanagara",
		"Vijayapura",
		"Yadgir",
	],
	Odisha: [
		"Anugul",
		"Balangir",
		"Baleshwar",
		"Bargarh",
		"Bhadrak",
		"Boudh",
		"Cuttack",
		"Debagarh",
		"Dhenkanal",
		"Gajapati",
		"Ganjam",
		"Jagatsinghapur",
		"Jajapur",
		"Jharsuguda",
		"Kalahandi",
		"Kandhamal",
		"Kendrapara",
		"Kendujhar",
		"Khordha",
		"Koraput",
		"Malkangiri",
		"Mayurbhanj",
		"Nabarangapur",
		"Nayagarh",
		"Nuapada",
		"Puri",
		"Rayagada",
		"Sambalpur",
		"Subarnapur",
		"Sundargarh",
	],
	AndhraPradesh: [
		"Anantapur",
		"Chittoor",
		"East Godavari",
		"Guntur",
		"Krishna",
		"Kurnool",
		"Sri Potti Sriramulu Nellore",
		"Prakasam",
		"Srikakulam",
		"Visakhapatnam",
		"Vizianagaram",
		"West Godavari",
		"Y.S.R. Kadapa",
	],
	ArunachalPradesh: [
		"Anjaw",
		"Changlang",
		"Dibang Valley",
		"East Kameng",
		"East Siang",
		"Kamle",
		"Kra Daadi",
		"Kurung Kumey",
		"Lepa Rada",
		"Lohit",
		"Longding",
		"Lower Dibang Valley",
		"Lower Siang",
		"Lower Subansiri",
		"Namsai",
		"Pakke Kessang",
		"Papum Pare",
		"Shi Yomi",
		"Siang",
		"Tawang",
		"Tirap",
		"Upper Siang",
		"Upper Subansiri",
		"West Kameng",
		"West Siang",
	],
	Jharkhand: [
		"Bokaro",
		"Chatra",
		"Deoghar",
		"Dhanbad",
		"Dumka",
		"East Singhbhum",
		"Garhwa",
		"Giridih",
		"Godda",
		"Gumla",
		"Hazaribagh",
		"Jamtara",
		"Khunti",
		"Koderma",
		"Latehar",
		"Lohardaga",
		"Pakur",
		"Palamu",
		"Ramgarh",
		"Ranchi",
		"Sahibganj",
		"Saraikela-Kharsawan",
		"Simdega",
		"West Singhbhum",
	],
	WestBengal: [
		"Alipurduar",
		"Bankura",
		"Birbhum",
		"Cooch Behar",
		"Dakshin Dinajpur",
		"Darjiling",
		"Hooghly",
		"Howrah",
		"Jalpaiguri",
		"Jhargram",
		"Kalimpong",
		"Kolkata",
		"Maldah",
		"Murshidabad",
		"Nadia",
		"North 24 Parganas",
		"Paschim Medinipur",
		"Barddhaman",
		"Purba Medinipur",
		"Puruliya",
		"South 24 Parganas",
		"Uttar Dinajpur",
	],
	Punjab: [
		"Amritsar",
		"Barnala",
		"Bathinda",
		"Faridkot",
		"Fatehgarh Sahib",
		"Fazilka",
		"Firozpur",
		"Gurdaspur",
		"Hoshiarpur",
		"Jalandhar",
		"Kapurthala",
		"Ludhiana",
		"Mansa",
		"Moga",
		"Sri Muktsar Sahib",
		"Pathankot",
		"Patiala",
		"Rupnagar",
		"Sahibzada Ajit Singh Nagar",
		"Sangrur",
		"Shahid Bhagat Singh Nagar",
		"Tarn Taran",
	],
	Haryana: [
		"Ambala",
		"Bhiwani",
		"Charkhi Dadri",
		"Faridabad",
		"Fatehabad",
		"Gurugram",
		"Hisar",
		"Jhajjar",
		"Jind",
		"Kaithal",
		"Karnal",
		"Kurukshetra",
		"Mahendragarh",
		"Nuh",
		"Palwal",
		"Panchkula",
		"Panipat",
		"Rewari",
		"Rohtak",
		"Sirsa",
		"Sonipat",
		"Yamunanagar",
	],
	JammuAndKashmir: [
		"Anantnag",
		"Bandipore",
		"Baramula",
		"Budgam",
		"Doda",
		"Ganderbal",
		"Jammu",
		"Kathua",
		"Kishtwar",
		"Kulgam",
		"Kupwara",
		"Poonch",
		"Pulwama",
		"Rajouri",
		"Ramban",
		"Reasi",
		"Samba",
		"Shopian",
		"Srinagar",
		"Udhampur",
	],
	Kerala: [
		"Alappuzha",
		"Ernakulam",
		"Idukki",
		"Kannur",
		"Kasaragod",
		"Kollam",
		"Kottayam",
		"Kozhikode",
		"Malappuram",
		"Palakkad",
		"Pathanamthitta",
		"Thiruvananthapuram",
		"Thrissur",
		"Wayanad",
	],
	Uttarakhand: [
		"Almora",
		"Bageshwar",
		"Chamoli",
		"Champawat",
		"Dehradun",
		"Haridwar",
		"Nainital",
		"Pauri Garhwal",
		"Pithoragarh",
		"Rudraprayag",
		"Tehri Garhwal",
		"Udham Singh Nagar",
		"Uttarkashi",
	],
	HimachalPradesh: [
		"Bilaspur",
		"Chamba",
		"Hamirpur",
		"Kangra",
		"Kinnaur",
		"Kullu",
		"Lahaul And Spiti",
		"Mandi",
		"Shimla",
		"Sirmaur",
		"Solan",
		"Una",
	],
	Manipur: [
		"Bishnupur",
		"Chandel",
		"Churachandpur",
		"Imphal East",
		"Imphal West",
		"Jiribam",
		"Kakching",
		"Kamjong",
		"Kangpokpi",
		"Noney",
		"Pherzawl",
		"Senapati",
		"Tamenglong",
		"Thoubal",
		"Ukhrul",
	],
	Nagaland: [
		"Dimapur",
		"Kiphire",
		"Kohima",
		"Longleng",
		"Mokokchung",
		"Mon",
		"Peren",
		"Phek",
		"Tuensang",
		"Wokha",
		"Zunheboto",
	],
	Meghalaya: [
		"East Garo Hills",
		"East Jaintia Hills",
		"East Khasi Hills",
		"North Garo Hills",
		"Ri Bhoi",
		"South Garo Hills",
		"South West Garo Hills",
		"South West Khasi Hills",
		"West Garo Hills",
		"West Jaintia Hills",
		"West Khasi Hills",
	],
	Tripura: [
		"Dhalai",
		"Gomati",
		"Khowai",
		"North Tripura",
		"Sepahijala",
		"South Tripura",
		"Unokoti",
		"West Tripura",
	],
	Sikkim: [
		"East District",
		"North District",
		"Pakyong",
		"Soreng",
		"South District",
		"West District",
	],
	Goa: ["North Goa", "South Goa"],
	Delhi: [
		"Central Delhi",
		"East Delhi",
		"New Delhi",
		"North Delhi",
		"North East Delhi",
		"North West Delhi",
		"Shahdara",
		"South Delhi",
		"South East Delhi",
		"South West Delhi",
		"West Delhi",
	],
	Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],

	Chandigarh: ["Chandigarh"],

	Ladakh: ["Kargil", "Leh(Ladakh)"],

	Lakshadweep: ["Lakshadweep"],

	AndamanAndNicobarIslands: [
		"Nicobars",
		"North & Middle Andaman",
		"South Andaman",
	],
	DadraAndNagarHaveliAndDamanAndDiu: ["Dadra & Nagar Haveli", "Daman", "Diu"],
	Mizoram: [
		"Aizawl",
		"Champhai",
		"Kolasib",
		"Lawngtlai",
		"Lunglei",
		"Mamit",
		"Saiha",
		"Serchhip",
		"Hnahthial",
		"Khawzawl",
		"Saitual",
	],
}

// ============================
// HELPERS
// ============================
const normalize = (s: string) => s.trim().toLowerCase().replace(/\s+/g, " ")

// biome-ignore lint/suspicious/noExplicitAny: <explanation>
const featureMap = new Map<string, any>()

for (const f of geojson.features) {
	const name = f?.properties?.shapeName
	if (!name) continue
	featureMap.set(normalize(name), f)
}

// ============================
// OUTPUT
// ============================
const outDir = "./public/geojson/india/states"
fs.mkdirSync(outDir, { recursive: true })

// ============================
// GLOBAL STATS
// ============================
let totalMatched = 0
let totalMissing = 0

console.log("\n🚀 Starting split process...\n")

// ============================
// PROCESS STATES
// ============================
for (const [state, districts] of Object.entries(stateDistrictMap)) {
	const features: any[] = []
	const missing: string[] = []

	for (const d of districts) {
		const f = featureMap.get(normalize(d))

		if (!f) {
			missing.push(d)
			continue
		}

		features.push(f)
		totalMatched++
	}

	totalMissing += missing.length

	if (features.length === 0) {
		console.warn(`⚠ ${state}: skipped (no matches)`)
		continue
	}

	const fileName = state.toLowerCase().replace(/\s+/g, "-")

	fs.writeFileSync(
		path.join(outDir, `${fileName}.json`),
		JSON.stringify({
			type: "FeatureCollection",
			features,
		}),
	)

	console.log(`✔ ${state}: ${features.length} districts`)

	if (missing.length > 0) {
		console.log(`   ↳ Missing: ${missing.length}`)
		console.log("   ", missing.join(", "))
	}
}

// ============================
// SUMMARY
// ============================
console.log("\n📊 SUMMARY")
console.log(`✔ Matched: ${totalMatched}`)
console.log(`❌ Missing: ${totalMissing}`)
console.log("\n🎉 Done")
