import type { Map as MaplibreMap } from "maplibre-gl"
import {
	SYMBOL_SORT_KEY,
	TEXT_ALLOW_OVERLAP,
	TEXT_ANCHOR,
	TEXT_COLOR,
	TEXT_FIELD,
	TEXT_FONT,
	TEXT_HALO_BLUR,
	TEXT_HALO_COLOR,
	TEXT_HALO_WIDTH,
	TEXT_LETTER_SPACING,
	TEXT_OFFSET,
	TEXT_PADDING,
	TEXT_SIZE,
} from "./labels"

export function addPlaceLayers(map: MaplibreMap) {
	// Marker dots, sized by tier.
	map.addLayer({
		id: "osm-place-dots",
		type: "circle",
		source: "osm-places",
		paint: {
			"circle-radius": [
				"interpolate",
				["linear"],
				["zoom"],
				8,
				["match", ["get", "place"], "city", 5.4, "town", 3.6, 0],
				11,
				[
					"match",
					["get", "place"],
					"city",
					5.4,
					"town",
					3.6,
					"village",
					0.5,
					0,
				],
				13,
				[
					"match",
					["get", "place"],
					"city",
					5.4,
					"town",
					3.6,
					"village",
					2.4,
					1.2,
				],
				16,
				[
					"match",
					["get", "place"],
					"city",
					6.4,
					"town",
					4.6,
					"village",
					3.4,
					2.2,
				],
			],
			"circle-color": [
				"match",
				["get", "place"],
				"city",
				"#ffffff",
				"town",
				"#dde7f4",
				"#a8b8cc",
			],
			"circle-opacity": [
				"interpolate",
				["linear"],
				["zoom"],
				8,
				["match", ["get", "place"], "city", 0.96, "town", 0.86, 0],
				11,
				[
					"match",
					["get", "place"],
					"city",
					0.96,
					"town",
					0.86,
					"village",
					0.3,
					0,
				],
				13,
				[
					"match",
					["get", "place"],
					"city",
					0.96,
					"town",
					0.86,
					"village",
					0.72,
					0.5,
				],
				16,
				[
					"match",
					["get", "place"],
					"city",
					0.96,
					"town",
					0.86,
					"village",
					0.82,
					0.7,
				],
			],
			"circle-stroke-color": "rgba(120, 180, 220, 0.55)",
			"circle-stroke-width": 1,
		},
	})

	// Labels (collision-aware).
	map.addLayer({
		id: "osm-place-labels",
		type: "symbol",
		source: "osm-places",
		layout: {
			"text-field": TEXT_FIELD,
			"text-font": TEXT_FONT,
			"text-size": TEXT_SIZE,
			"text-letter-spacing": TEXT_LETTER_SPACING,
			"text-offset": TEXT_OFFSET,
			"text-anchor": TEXT_ANCHOR,
			"text-padding": TEXT_PADDING,
			"text-allow-overlap": TEXT_ALLOW_OVERLAP,
			"symbol-sort-key": SYMBOL_SORT_KEY,
		},
		paint: {
			"text-color": TEXT_COLOR,
			"text-halo-color": TEXT_HALO_COLOR,
			"text-halo-width": TEXT_HALO_WIDTH,
			"text-halo-blur": TEXT_HALO_BLUR,
		},
	})
}
