import type { Map as MaplibreMap } from "maplibre-gl"

export function addRoadLayers(map: MaplibreMap) {
	// Soft tactical underglow — only meaningful on major routes.
	map.addLayer({
		id: "osm-road-glow",
		type: "line",
		source: "osm-roads",
		layout: { "line-cap": "round", "line-join": "round" },
		filter: [
			"in",
			["get", "highway"],
			["literal", ["motorway", "trunk", "primary", "secondary"]],
		],
		paint: {
			"line-color": "#7cc1f2",
			"line-blur": 5,
			"line-opacity": [
				"match",
				["get", "highway"],
				"motorway",
				0.26,
				"trunk",
				0.22,
				"primary",
				0.2,
				"secondary",
				0.14,
				0.1,
			],
			"line-width": [
				"interpolate",
				["linear"],
				["zoom"],
				9,
				[
					"match",
					["get", "highway"],
					"motorway",
					4,
					"trunk",
					3.5,
					"primary",
					3,
					"secondary",
					2,
					"tertiary",
					1.4,
					0.8,
				],
				13,
				[
					"match",
					["get", "highway"],
					"motorway",
					9,
					"trunk",
					8,
					"primary",
					7,
					"secondary",
					5,
					"tertiary",
					3.5,
					2.2,
				],
				16,
				[
					"match",
					["get", "highway"],
					"motorway",
					16,
					"trunk",
					14,
					"primary",
					12,
					"secondary",
					9,
					"tertiary",
					6,
					4,
				],
			],
		},
	})

	// Crisp light core.
	map.addLayer({
		id: "osm-road-core",
		type: "line",
		source: "osm-roads",
		layout: { "line-cap": "round", "line-join": "round" },
		paint: {
			"line-color": [
				"match",
				["get", "highway"],
				"motorway",
				"rgba(225, 240, 254, 0.94)",
				"trunk",
				"rgba(215, 232, 250, 0.88)",
				"primary",
				"rgba(205, 224, 246, 0.78)",
				"secondary",
				"rgba(195, 220, 248, 0.74)",
				"tertiary",
				"rgba(175, 200, 226, 0.52)",
				"unclassified",
				"rgba(150, 180, 205, 0.38)",
				"rgba(140, 170, 195, 0.32)",
			],
			"line-width": [
				"interpolate",
				["linear"],
				["zoom"],
				9,
				[
					"match",
					["get", "highway"],
					"motorway",
					1.4,
					"trunk",
					1.2,
					"primary",
					1.0,
					"secondary",
					0.7,
					"tertiary",
					0.4,
					0.3,
				],
				13,
				[
					"match",
					["get", "highway"],
					"motorway",
					3.4,
					"trunk",
					3.0,
					"primary",
					2.6,
					"secondary",
					1.9,
					"tertiary",
					1.3,
					0.9,
				],
				16,
				[
					"match",
					["get", "highway"],
					"motorway",
					6.5,
					"trunk",
					5.6,
					"primary",
					4.8,
					"secondary",
					3.6,
					"tertiary",
					2.4,
					1.6,
				],
			],
		},
	})
}
