services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/DOCKERFILE

    working_dir: /workspace

    user: "1000:1000"

    volumes:
      - ..:/workspace
      - bun-cache:/home/devuser/.bun

    command: sleep infinity

    ports:
      - "3000:3000"

    tty: true

volumes:
  bun-cache: