services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/DOCKERFILE

    working_dir: /workspace

    volumes:
      - ..:/workspace
      - bun-cache:/home/devuser/.bun
      - vite-cache:/workspace/node_modules/.vite

    command: sleep infinity

    ports:
      - "3000:3000"

    tty: true

volumes:
  bun-cache:
  vite-cache: