/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as StateMapRouteImport } from './routes/state-map'
import { Route as MapRouteImport } from './routes/map'
import { Route as GisRouteImport } from './routes/gis'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StateIndexRouteImport } from './routes/$state/index'
import { Route as StateDistrictIndexRouteImport } from './routes/$state/$district/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const StateMapRoute = StateMapRouteImport.update({
  id: '/state-map',
  path: '/state-map',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateIndexRoute = StateIndexRouteImport.update({
  id: '/$state/',
  path: '/$state/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateDistrictIndexRoute = StateDistrictIndexRouteImport.update({
  id: '/$state/$district/',
  path: '/$state/$district/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gis': typeof GisRoute
  '/map': typeof MapRoute
  '/state-map': typeof StateMapRoute
<<<<<<< HEAD
=======
  '/test': typeof TestRoute
>>>>>>> origin/master
  '/$state/': typeof StateIndexRoute
  '/$state/$district/': typeof StateDistrictIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gis': typeof GisRoute
  '/map': typeof MapRoute
  '/state-map': typeof StateMapRoute
<<<<<<< HEAD
=======
  '/test': typeof TestRoute
>>>>>>> origin/master
  '/$state': typeof StateIndexRoute
  '/$state/$district': typeof StateDistrictIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gis': typeof GisRoute
  '/map': typeof MapRoute
  '/state-map': typeof StateMapRoute
<<<<<<< HEAD
=======
  '/test': typeof TestRoute
>>>>>>> origin/master
  '/$state/': typeof StateIndexRoute
  '/$state/$district/': typeof StateDistrictIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gis'
    | '/map'
    | '/state-map'
<<<<<<< HEAD
=======
    | '/test'
>>>>>>> origin/master
    | '/$state/'
    | '/$state/$district/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gis'
    | '/map'
    | '/state-map'
<<<<<<< HEAD
=======
    | '/test'
>>>>>>> origin/master
    | '/$state'
    | '/$state/$district'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gis'
    | '/map'
    | '/state-map'
<<<<<<< HEAD
=======
    | '/test'
>>>>>>> origin/master
    | '/$state/'
    | '/$state/$district/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GisRoute: typeof GisRoute
  MapRoute: typeof MapRoute
  StateMapRoute: typeof StateMapRoute
<<<<<<< HEAD
=======
  TestRoute: typeof TestRoute
>>>>>>> origin/master
  StateIndexRoute: typeof StateIndexRoute
  StateDistrictIndexRoute: typeof StateDistrictIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state-map': {
      id: '/state-map'
      path: '/state-map'
      fullPath: '/state-map'
      preLoaderRoute: typeof StateMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/': {
      id: '/$state/'
      path: '/$state'
      fullPath: '/$state/'
      preLoaderRoute: typeof StateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/$district/': {
      id: '/$state/$district/'
      path: '/$state/$district'
      fullPath: '/$state/$district/'
      preLoaderRoute: typeof StateDistrictIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GisRoute: GisRoute,
  MapRoute: MapRoute,
  StateMapRoute: StateMapRoute,
<<<<<<< HEAD
=======
  TestRoute: TestRoute,
>>>>>>> origin/master
  StateIndexRoute: StateIndexRoute,
  StateDistrictIndexRoute: StateDistrictIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
